name: detective
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - seaborn
  - python=3.7.7
  - matplotlib
  - scipy
  - scikit-image
  - pip
  - pip:
      - datascience
      - dcor
  
